-- MySQL Script generated by MySQL Workbench
-- Tue Mar 10 09:25:50 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`firma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`firma` (
  `idfirma` INT NOT NULL AUTO_INCREMENT,
  `firmaStatus` ENUM('Aktiv', 'Inaktiv') NOT NULL,
  `firmaOrganisasjonsnummer` VARCHAR(9) NULL,
  `firmaNavn` VARCHAR(128) NULL,
  `firmaAdresse` VARCHAR(128) NULL,
  `firmaTlf` VARCHAR(15) NULL,
  `firmaKundeSiden` DATE NULL,
  `firmaPostnr` VARCHAR(4) NULL,
  PRIMARY KEY (`idfirma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kontaktperson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kontaktperson` (
  `idkontaktperson` INT NOT NULL AUTO_INCREMENT,
  `firma_idfirma` INT NOT NULL,
  `kontaktpersonStatus` ENUM('Aktiv', 'Inaktiv') NOT NULL,
  `kontaktpersonEtternavn` VARCHAR(128) NULL,
  `kontaktpersonFornavn` VARCHAR(64) NULL,
  `kontaktpersonTlf` VARCHAR(15) NULL,
  `kontaktpersonEpost` VARCHAR(128) NULL,
  `kontaktpersonDatoLagtTil` DATE NULL,
  PRIMARY KEY (`idkontaktperson`),
  INDEX `fk_kontaktperson_firma_idx` (`firma_idfirma` ASC) VISIBLE,
  CONSTRAINT `fk_kontaktperson_firma`
    FOREIGN KEY (`firma_idfirma`)
    REFERENCES `mydb`.`firma` (`idfirma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
